import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";

import "./globals.css";
import { Navigation } from "@/components/navigation";
import { Header } from "@/components/header";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.className} flex w-screen h-screen`}>
        <Navigation />
        <div className="h-full flex flex-col flex-1">
          <Header />
          <main className="w-full h-full bg-white overflow-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
