import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

// TODO 폰트 정하기
const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <nav></nav>
        {children}
      </body>
    </html>
  );
}
